### ISSUE TITLE
接入大模型后公众号自定义菜单和自定义回复失效问题

### ISSUE THREAD

**Issue by nlxxtw** [LuhangRui/qw-wechat-vercel#2]
大佬，不知如何解决，公众号接入大模型后，自定义菜单和自定义回复失效问题

**Comment by LuhangRui** [comment]
自定义菜单要通过接口设置，这个我没实现。自定义关键词回复的话，我文档里是有提到的，需要配置环境变量KEYWORD_REPLAY
